spring:
  application:
    name: project-module-user
  profiles:
    active: dev
  jackson:
    date-format: java.text.SimpleDateFormat
  sql:
    init:
      continue-on-error: true
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db-user
    username: admin
    password: pass
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
    database: postgresql
    open-in-view: true
    generate-ddl: true
server:
  port: 8080
